version: '3.1'

services:

  wordpress:
    image: wordpress:6.0
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: